### ISSUE TITLE
what's the problem?

### ISSUE THREAD

**Issue by windyGex** [WebReflection/ie8#20]
I just include ie8.js in the page.
and browser console log this:
```javascript
value failed on object: [object HTMLSelectElement] 对象不支持此操作
```
what can i do now?

**Comment by WebReflection** [comment]
use a `<!DOCTYPE html>` on  top of your pages

**Comment by WebReflection** [comment]
Just to be clear: I've actually no idea what you can do. There are tests pages, 190+ and nobody with this problem already reported. If you would like to help me understand what could be your problem you need to give me a page I can verify where is the problem,  what could it be,  and why is there.

Without that it could be anything I can only keep providing sentences like a "fortune teller" but I haven't much time these days so apologies if I won't come back.

To help further, this repository doesn't make automatically every page compatible with IE8 ... it's a long way commitment to support IE8 if you've never tried before and you have an already live product that never cared about IE8.

Problems could be everywhere because IE8 has problems everywhere.

If you find same problem with any of the current test pages and scripts, then I'll re-open this and try to  eventually fix it, if that's even possible.

Best Regards

**Comment by windyGex** [comment]
![image](https://cloud.githubusercontent.com/assets/197348/10037011/68a564da-61e2-11e5-99e8-136ac04d2efd.png)


I clone this repos and open index.html to run test cases. 3 tests failed, and console log error.
