### ISSUE TITLE
Cannot attach mousemove to document

### ISSUE THREAD

**Issue by neersighted** [WebReflection/ie8#24]
I have the following code:

    document.addEventListener "mousemove", (event = window.event) =>
      alert "move"

However, in IE8, the callback never fires.
This worked in IE >= 9 as well as Chrome and Firefox.

**Comment by WebReflection** [comment]
is that CoffeeScript?

**Comment by WebReflection** [comment]
Regardless, can you please provide vanilla JS examples that doesn't work? Because events are tested and  do work in IE8 .... without transpilers, of course.

**Comment by neersighted** [comment]
This does not appear to work:
    document.addEventListener("mousemove", function (event) {alert("move");});
While this does:
    document.attachEvent("onmousemove", function (event) {alert("move");});

**Comment by WebReflection** [comment]
I'm pretty sure that code does works but I'll check again when I have some time which is probably never before the 7th. Events do work and are tested, so please try to be sure you are in  a clean standard env.

**Comment by neersighted** [comment]
I am using other event handling code with addEventListener just fine... `mousemove` is the only troublesome event.

**Comment by WebReflection** [comment]
Hey ... WTF (not to you, actually to me) that was indeed a very silly and concrete bug.

Thanks, I'm used to set events eventually to `document.documentElement` and rarely to the document itself, which is why I haven't spot this before.

Funny apparently also nobody else has spot this before ... how weird!

Please use `0.2.11` which fixes this problem, apologizes for my initial skepticism, I don;'t trust much transpiled JS when it comes to legacy support.

Hope this works and you can close this bug after checking.

Best Regards

**Comment by WebReflection** [comment]
P.S. I had time, it was an easy one to spot ... me => stupid ^_^

**Comment by neersighted** [comment]
That fixed it, thanks!

On another notes, thanks a ton for IE8 and DOM4. It makes it actually possible to use modern code (and forget about having to support many methods of doing the same thing) when I have to support IE8 (game I code for embeds IE).

**Comment by WebReflection** [comment]
Just remember to test for real on real IE8 too and happy worry-free coding
